apiVersion: v1
kind: pod 
metadata:
  name: configmap-env-demo
spec:
  containers:
    - name: configmap-demo
      image: alpine
      command: ["sleep", "3600"]
      env:
       - name: PLAYER_LIVE
         valueFrom:
           configMapKeyRef:
             name: player-pro-demo
             key: player_lives
       - name: PROPERTIES_FILE_NAME
         valueFrom:
           configMapKeyRef:
             name: player-pro-demo
             key: properties_file_name
       - name: SECRET_USERNAME
         valueFrom:
          secretKeyRef:
            name: example-user
            key: username
       - name: SECRET_PASSWORD
         valueFrom:
           secretKeyRef:
            name: example-password
            key: password 

