apiVersion: v1
kind: Pod
metadata:
  name: config-map-vol-demo
spec:
   containers:
    - name: config-map-vol-demo
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - name: player-map
          mountPath: /etc/config/configmap
        - name: player-secret
          mountPath: /etc/config/secret
   volumes: 
        - name: player-map
          configMap:
           name: player-pro-demo
        - name: player-secret
          secret:
            secretName: example-secret