apiVersion: v1
kind: Pod
metadata:
  name: liveness-healthcheck
spec:
  containers:
    - name: app
      image: k8s.gcr.io/busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      args:
        - /bin/bash
        - c
        - touch /tmp/health; sleep 60; rm -rf /tmp/health; sleep 60
      livenessProbe:
          exec:
            command:
              - cat 
              - /tmp/health
          initialDelaySecond: 5
          periodSecond: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-healthcheck-http
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: k8s.gcr.io/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySecond: 3
      periodSecond: 3