apiVersion: v1
kind: Pod
metadata: 
  name: two-container-pod
spec:
  containers:
    - name: debian-container
      image: debian
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
      volmeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/sh"]
      args:  ["-c", "echo Hello from Secondary Containers > /pod-data/index.html"]

    - name: nginx-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m" 
      volumeMounts:
       - name: shared-data
         mountPath: /usr/share/nginx/html
  vlomes:
    - name: shared-data
      emptyDir: {}