apiVersion: v1
kind: Pod 
metadata: 
  name: onfailure-restart
spec:
    restartPolicy: OnFailure
    containers:
     - name: failure
       image: alpine
       resources:
         limits:
           memory: "128Mi"
           cpu: "250m"
       command: ['sh', '-c', 'sleep 20', 'Dummy Command' ]
       