apiVersion: v1
kind: Pod 
metadata: 
  name: readiness-hc
spec:
  containers:
    - name: myapp-red
      image: k8s.gcr.io/nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3