apiVersion: v1
kind: Pod 
metadata:
  name: startup-probe
spec: 
   containers:
     - name: app
       image: k8s.gcr.io/nginx
       resources:
         limits:
           memory: "64Mi"
           cpu: "200m"
       startupProbe:
         httpGet:
          path: /
          port: 80
         failureThreshold: 30
         periodSecond: 3
