apiVersion: apps/v1
kind: Deployment
metadata:
  name: chef-server
  labels:
    app: chef-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chef-server
  template:
    metadata:
      labels:
        app: chef-server
    spec:
      containers:
      - name: chef-server
        image: chef/chef:17.10.119
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        command:
         - "/bin/sh"
        args:
         - '-c'
         - echo Hello from Chef Server ; sleep 3600
      - name: ubuntu-server
        image: 'ubuntu:20.04' 
        ports: 
         - containerPort: 8090
        command:
         - "/bin/sh"
         - '-c'
         - echo  Hello this is ubuntu server; sleep 4600 
