apiVersion: apps/v1
kind: Deployment
metatdata:
  name: nginx-server
  labels:
    app: myapp
    env: experiment
    type: etl
spec:
  template:
    metadata:
      name: nginx-server
      labels:
        app: myapp
        env: experiment
        type: etl
    spec:
      containers:
        - name: nginx
          image: nginx:default
          resources:
            limits:
              cpu: 200m
              memory: 164Mi
  replicas: 3
  selector:
    matchLabels:
      type: etl
