apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: development
subjects:
- kind: user
  name: DevUser
  apiGroups: rbac.authorization.k8s.io/v1
roleRef: 
  kind: Role 
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io/v1
  