apiVersion: v1
kind: Pod
metadata: 
  name: share-vol
spec:
  volumes:
    - name: share-vol
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
       - name: share-vol
         mountPath: /usr/share/nginx/html
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
    - name: debian
      image: debian
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
      command: 
        - "/bin/sh"
        - "-c"
      args:
       - while true; do date >> /html/index.html; sleep 5 ; done
      volumeMounts:
        - name: share-vol
          mountPath: /html
